name: Publish

on:
  push:
    branches: [main]
    tags: ['*']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11.0.x
      - name: Setup .NET 6.0
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: Restore tools
        run: dotnet tool restore
      - name: Run the build script
        uses: cake-build/cake-action@v1
        env:
          COVERALLS_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
          NUGET_API_URL: https://api.nuget.org/v3/index.json
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NUGET_PRE_API_KEY: ${{ secrets.GITHUB_TOKEN }}
          NUGET_PRE_API_URL: https://nuget.pkg.github.com/benfoster/index.json
        with:
          target: Publish
